### ISSUE TITLE
incompatible with windows 3.0.0

### ISSUE THREAD

**Issue by gavit** [TAMUArch/cookbook.windows_ad#109]
https://github.com/chef-cookbooks/windows V 3.0.0 and higher is not backwards compatible. When running this recipe you now get a 
`NoMethodError: undefined method "feature" for Custom resource                                  windows_feature_dism from cookbook windows`

**Comment by derekgroh** [comment]
What version of the cookbook are you running?

**Comment by derekgroh** [comment]
Hello,

Please use version 0.5.5 of the windows_ad cookbook to resolve the issue.

Thanks,

Derek
