### ISSUE TITLE
not all boxes have `ActiveDirectory Powershell`

### ISSUE THREAD

**Issue by joshoohaah** [TAMUArch/cookbook.windows_ad#113]
not all windows machines have the feature `ActiveDirectory Powershell`.  to install it as a windows feature i had to install `RSAT-AD-PowerShell` 

Error:
```
         * windows_feature[ActiveDirectory-Powershell] action install
           * windows_feature_dism[ActiveDirectory-Powershell] action install[2017-08-08T18:35:57+00:00] WARN: Requested feature ActiveDirectory-Powershell is not available on this system.
        (up to date)
```

Here is the resource I used to install the powershell module
```
windows_feature 'RSAT-AD-PowerShell' do
  action :install
  all true
  install_method :windows_feature_powershell
end

```

**Comment by derekgroh** [comment]
What version of OS did you experience this on?

**Comment by joshoohaah** [comment]
Windows 2012R2

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by derekgroh** [comment]
The current provider is written to use dism instead of powershell. 

Under dism the feature is named ActiveDirectory-Powershell, while in powershell it is named RSAT-AD-Powershell. 

This has been tested and confirmed working with both providers on version 6.3.9600
