### ISSUE TITLE
DCPromo doesn't get executed?

### ISSUE THREAD

**Issue by xyker** [TAMUArch/cookbook.windows_ad#114]
When trying to create a replica or read-only domain controller, it appears DCpromo does not get executed to finish up the installation of the DC.  All of the necessary packages are installed via Chef but the server manager notifies that there are still post-installation tasks.  Manually going through these tasks does complete successfully.

Script used looks similar to the following:

```
windows_ad_domain "contoso.com" do
  action :create
  type "read-only"
  safe_mode_pass "Passw0rd"
  domain_user "Administrator"
  domain_pass "Passw0rd"
end
```

**Comment by derekgroh** [comment]
Hello, 

What version of OS did you encounter this on?
What version of the cookbook are you running?

**Comment by xyker** [comment]
Thank you very much for the quick response.  Apologies on my lack of information.

Windows Server 2012 R2 Datacenter
windows_ad 0.6.1

**Comment by derekgroh** [comment]
The error is:
A parameter cannot be found that matches parameter name 'SafeModeAdministratorPassword'.
As it is not a supported option in the command Add-ADDSReadOnlyDomainControllerAccount

https://technet.microsoft.com/en-us/library/hh974718(v=wps.630).aspx 

I do not see the same issue with replica, but did not perform a full test.

**Comment by derekgroh** [comment]
I didn't encounter any issues with replica, but read only domain controllers are going to take some effort to work in properly. I'm working on switching over the resource to Chef 12.5 and using powershell for the main resource. I'll add this to the stack.

**Comment by d-mcd** [comment]
Having very similar issue except for forest creation.
When creating a new forest; DS and DNS features are installed but DC promotion is always left to complete.
Windows Server 2016 Base Datacenter
windows_ad 0.6.1

No errors are seen during chef-client run or anything that stand out in Windows EVL.

Code used:

```
windows_ad_domain "myfqdn.local" do
  action :create
  type "forest"
  safe_mode_pass ad_creds['users']['adadmin']['password']
  options ({ "ForestMode" => "Win2012R2",
             "InstallDNS" => nil
           })
end
```

**Comment by derekgroh** [comment]
@d-mcd Do you create the instance before converging?

**Comment by d-mcd** [comment]
Thank you for the reply.
To be clear I am using Chef provisioner in Terraform when standing up my EC2 Windows 2016 instance. Winrm will keep attempting connects until the instance is available. (Time out set to 10 minutes in connection block). Once the winrm connection is established the Chef bootstrap process starts. 
Note: I do on occasion encounter an error related to a PS script not being available in C:\Temp. Guessing a timing issue. Typically, if I do encounter that error a destroy and apply will run successfully the next time. The only consistent issue I am having is the DC promotion is never performed.

**Comment by derekgroh** [comment]
@d-mcd Reported via chef or actually checking? Do to the reboot of the node as part of the process, we've not found a way to report back to chef correctly that the node is now a DC.

**Comment by d-mcd** [comment]
Actually checking.
![image](https://user-images.githubusercontent.com/33379985/32528785-ed977802-c402-11e7-803b-c852b994a8d7.png)

**Comment by d-mcd** [comment]
Here is the output for the end of the Chef run.

```
aws_instance.ad-dc (chef):       - install Windows feature DirectoryServices-DomainController

aws_instance.ad-dc (chef):         - re-run ohai and merge results into node attributes
aws_instance.ad-dc (chef):
aws_instance.ad-dc (chef):
aws_instance.ad-dc (chef): Recipe: windows_ad::fqdn.local
aws_instance.ad-dc (chef):   * execute[net user "Administrator" "P@ss0rd"] action run
aws_instance.ad-dc (chef):     - execute net user "Administrator" "P@ss0rd"
aws_instance.ad-dc (chef):   * windows_ad_domain[fqdn.local] action create

aws_instance.ad-dc (chef):     * powershell_script[create_domain_fqdn.local] action run
aws_instance.ad-dc: Still creating... (12m30s elapsed)
aws_instance.ad-dc: Still creating... (12m40s elapsed)
aws_instance.ad-dc: Still creating... (12m50s elapsed)
aws_instance.ad-dc: Still creating... (13m0s elapsed)
aws_instance.ad-dc: Still creating... (13m10s elapsed)
aws_instance.ad-dc: Still creating... (13m20s elapsed)
aws_instance.ad-dc: Still creating... (13m30s elapsed)
aws_instance.ad-dc: Still creating... (13m40s elapsed)
aws_instance.ad-dc: Still creating... (13m50s elapsed)
aws_instance.ad-dc: Still creating... (14m0s elapsed)

aws_instance.ad-dc (chef):       - execute "C:\Windows\system32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NonInteractive -NoProfile -ExecutionPolicy Bypass -InputFormat None -File "C:/Users/ADMINI~1/AppData/Local/Temp/chef-script20171108-2504-wipalj.ps1"
aws_instance.ad-dc (chef):
aws_instance.ad-dc (chef):
aws_instance.ad-dc (chef): Running handlers:
aws_instance.ad-dc (chef): Running handlers complete
aws_instance.ad-dc (chef): Chef Client finished, 38/46 resources updated in 03 minutes 44 seconds
aws_instance.ad-dc: Creation complete after 14m3s (ID: i-01cb0925df311cd63)

```

**Comment by derekgroh** [comment]
Let me know what progress you can make in the command output that chef runs and we can pick up from there.

**Comment by d-mcd** [comment]
Have not been able to capture the command that is being built and the PS script file is removed from disk once chef run is complete. Is there a way to prevent that from being removed?And not seeing any issues in chef log with debug on.
However; after upgrading chef-client cookbook from 8.1.8 -> 9.0.0 and windows cookbook from 3.1.3 -> 3.3.0,the DC promotion step has completed for the last three runs.

**Comment by derekgroh** [comment]
We're taking some effort to clean up older issues for this repository. Please reply if you still wish for this to be worked on.
