### ISSUE TITLE
Forest domain creation causing chef run to fail

### ISSUE THREAD

**Issue by joshoohaah** [TAMUArch/cookbook.windows_ad#115]
When I create an AD forest.  the chef run always fails/times out on creation.  Then when I run it again I can get to the next step and then the users are deployed.  I have seen that windows when it turns a box into a AD domain controller, it does some funky things to local users.  Is this why the run fails halfway all the time? or am I calling this wrong?

here is the error message
```
         * windows_ad_domain[test-kitchen.com] action create

         * reboot[now] action request_reboot[2017-08-17T14:10:20+00:00] WARN: Reboot requested:'now'

           - request a system reboot to occur if the run succeeds
         * powershell_script[create_domain_test-kitchen.com] action run
       [WinRM]  returned in cleanup with error: Could not decrypt NTLM message. ().
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #converge action: [WinRM::WinRMAuthorizationError] on server-windows-2012-sysprep
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

and here is the code block calling this section:
```
windows_ad_domain node['dcar_domain_controller']['domain_name'] do
  action :create
  type 'forest'
  safe_mode_pass node['dcar_domain_controller']['admin_password']
  domain_pass node['dcar_domain_controller']['admin_password']
  domain_user node['dcar_domain_controller']['domain_admin']
  options(
    'DomainNetbiosName' => node['dcar_domain_controller']['domain_prefix']
  )

  restart true
  notifies :request_reboot, 'reboot[now]', :immediately
end
# end

# #restart after
reboot 'now' do
  action :nothing
  reason 'Cannot continue Chef run without a reboot.'
  delay_mins 2
end

```
any help is much appreciated!

**Comment by derekgroh** [comment]
Perhaps, kocal users aren't allowed on a domain controller (unless it is RO) and the local administrator is converted to the system account for the domain.

You shouldn't need the `notifies :request_reboot` as the `restart true` prevents the `-norebootoncompletion` which results in the system rebooting after setup as a DC.

**Comment by joshoohaah** [comment]
thanks @derekgroh for the `reboot` comment.  Yeah I realized I didn't need it because you have an attribute set in your resource that handles this. I was experimenting to see if i could avoid having my chef run fail for this DC creation.

So is that the normal thing then @derekgroh that the run will timeout/fail once it creates as a DC. then the next run will work?

**Comment by derekgroh** [comment]
@joshoohaah my results are that the default recipe will produce a successful chef run with desired results, the setup_forest will fail to compete the Chef run (node reboots out from Ohai) but successfully creates a DC. 

I've been trying to test a method to allow Chef to reboot the node so that the run succeeds, but have been unsuccessful as of yet, my main goal is to update to the new resource providers to remove to pins to chef_version and windows cookbook dependency, but if you have any thoughts on the matter, please let me know.
