### ISSUE TITLE
Cannot add user to domain - dsadd failed:The parameter is incorrect.

### ISSUE THREAD

**Issue by binpath** [TAMUArch/cookbook.windows_ad#117]
windows_ad_user[cfxadm] action create

           ================================================================================
           Error executing action `create` on resource 'windows_ad_user[cfxadm]'
           ================================================================================

           RuntimeError
           ------------
           Failed to execute command.
           STDOUT:
           STDERR: dsadd failed:The parameter is incorrect.

           type dsadd /? for help.

           Resource Declaration:
           ---------------------
           # In C:/Users/ADMINI~1/AppData/Local/Temp/kitchen/cache/cookbooks/nvs_ad/recipes/sapusers.rb

            43:   windows_ad_user 'cfxadm' do
            44:     action :create
            45:     domain_name 'nvsdev.novis.cl'
            46:     ou 'Users'
            47:     options h_user
            48:     cmd_user user
            49:     cmd_pass pwd
            50:     cmd_domain fqdn
            51:   end
            52:
            53: end

           Compiled Resource:
           ------------------
           # Declared in C:/Users/ADMINI~1/AppData/Local/Temp/kitchen/cache/cookbooks/nvs_ad/recipes/sapusers.rb:43:in `from_file'

           windows_ad_user("cfxadm") do
             action [:create]
             default_guard_interpreter :default
             declared_type :windows_ad_user
             cookbook_name "nvs_ad"
             recipe_name "sapusers"
             domain_name "dev.contoso.com"
             ou "Users"
             options {"samid"=>"cfxadm@dev.contoso.com", "upn"=>"cfxadm@dev.contoso.com", "fn"=>"cfxadm", "ln"=>"cfxadm", "display"=>"cfxadm", "disabled"=>"no", "mustchpwd"=>"no", "pwd"=>"XXXXXXXXGFDWGFEGTR"·$%"·&%"}
             cmd_user "usrsapchef@dev.contoso.com"
             cmd_pass "!fsdagavfdhahbw"
             cmd_domain "dev.contoso.com"
           end

           System Info:
           ------------
           chef_version=13.8.5
           platform=windows
           platform_version=6.3.9600
           ruby=ruby 2.4.3p205 (2017-12-14 revision 61247) [x64-mingw32]
           program_name=C:/opscode/chef/bin/chef-client
           executable=C:/opscode/chef/bin/chef-client

**Comment by derekgroh** [comment]
Hello,

Can you provide the metadata or berksfile for nvs_ad?

**Comment by binpath** [comment]
Sorry you can close it!
I notice that my DNS was badly placed.

I'm going to open another issue regarding the windows_ad_group resource that in the exists? method in is not passing user, domain, pwd for the helper.

**Comment by derekgroh** [comment]
Glad to hear it.
