### ISSUE TITLE
Cannot add user to domain

### ISSUE THREAD

**Issue by binpath** [TAMUArch/cookbook.windows_ad#119]
In the node I cannot add user to domain if the domain admin user have never logged on. 

`[2018-05-08T18:31:23-03:00] INFO: windows_ad_user[create cfxadm]

           ================================================================================
           Error executing action `create` on resource 'windows_ad_user[cfxadm]'
           ================================================================================

           RuntimeError
           ------------
           Failed to execute command.
           STDOUT:
           STDERR: dsadd failed:The parameter is incorrect.`

The if I Login to the machine manually and create a profile the creation passes through.

`* windows_ad_user[cfxadm] action create[2018-05-08T18:57:33-03:00] INFO: Processing windows_ad_user[cfxadm] action create (nvs_ad::sapusers line 68)
       [2018-05-08T18:57:33-03:00] INFO: Processing windows_ad_user[cfxadm] action create (nvs_ad::sapusers line 68)`

**Comment by derekgroh** [comment]
Can you provide your entire run list?

**Comment by binpath** [comment]
Hi @derekgroh, 
My run-list is just a wrapper cookbook  recipe[nvs_ad::createusers]

First y modify some secedit.sdb so we can don't have the error with CreateProcessAsUserW.
Then we call the windows_ad_user resource. 

what i did is to log with powershell_script with property flags -LoadUserProfile for now it helps, but the helper in the mixlib/shellout can't run the command if the profile is not loaded.

kind regards, 
César Felce

**Comment by derekgroh** [comment]
All the same, I'm trying to gain context to understand if it is an issue with how windows approaches the resource or the resource itself. The more information you can provide the easier it is for me to reproduce to investigate.

**Comment by binpath** [comment]
@derekgroh, 
I'm trying to do the following scenario:
-------              -------
| DCO | <----- | NODE |
--------            --------

I create the node in VMware and we added to the domain with chef-provisioning, So the node when is ready is already added to the computers in the AD.

Then In the Node I run the windows_ad_user resource, using the domain admin user, I have to add the 'Replace level access level token' so I can use the cmd_user, cmd_pass, and cmd_domain properties in your resource. 

`    adm_user = {
      'samid' => sidadm,
      'upn' => "#{sidadm}@#{fqdn}",
      'fn' => sidadm,
      'ln' => sidadm,
      'display' => sidadm,
      'disabled' => 'no',
      'mustchpwd' => 'no',
      'pwd' => 'xxxxx',
    }

    windows_ad_user sidadm do
      action :create
      domain_name fqdn
      ou node['ou']['users']
      options adm_user
      cmd_user user
      cmd_pass pwd
      cmd_domain fqdn
    end`

Then I receive the error
`[2018-05-09T11:38:17-03:00] INFO: windows_ad_user[create cfxadm]


           ================================================================================
           Error executing action `create` on resource 'windows_ad_user[cfxadm]'
           ================================================================================

           RuntimeError
           ------------
           Failed to execute command.
           STDOUT:
           STDERR: dsadd failed:The parameter is incorrect.

           type dsadd /? for help.`

Then I login in the Node with my domain admin user, and execute the recipe and then it works properly

kind regards,
binpath

**Comment by binpath** [comment]
@derekgroh dos you could replicarse The scenario or you need more information?

Kind regards,
César

**Comment by binpath** [comment]
@derekgroh can we have a session so I can show you? you will notice faster.. 
Let me try to explain it:
NODES: 
A. DomainController (no run-list)
B. One server Windows 2012 Server R2. (Provisioned with VMWare this add the machine to the domain  using customSpecs)
Runlist: 
     nvs_windows::secedit (this one add permission to node to runAs other user)
     nvs_ad::createusers (this one tries using the windows_ad_user resource)

The command build by the cookbook
`dsadd user "CN=cfxadm,CN=Users,DC=nvsdev,DC=novis,DC=cl" -u usrsapchef -p p@ssw0rd -d nvsdev.novis.cl -samid "cfxadm" -upn "cfxadm@nvsdev.novis.cl" -fn "cfxadm" -ln "cfxadm" -display "cfxadm" -disabled "no" -mustchpwd "no" -pwd "p@ssw0rd"`

error using chef

` ==========================================================================
       Error executing action `create` on resource 'windows_ad_user[cfxadm]'
       ==========================================================================

       RuntimeError
       ------------
       Failed to execute command.
       STDOUT:
       STDERR: dsadd failed:The parameter is incorrect.

       type dsadd /? for help.
`

If I login RDP with the administrator Built-in user in the node (B) and execute the command it works.
if I do it with chef run it as "usrsapchef", my domain admin user, it fails.

**Comment by derekgroh** [comment]
We're taking some effort to clean up older issues for this repository. Please reply if you still wish for this to be worked on.

**Comment by binpath** [comment]
@derekgroh ye we needed it and we did it, i think is the pull request that a made a long time ago.
