### ISSUE TITLE
Cannot remove 'USER' from 'OU' and 'GROUP' from 'OU' in AD using windows_ad cookbook

### ISSUE THREAD

**Issue by saivv** [TAMUArch/cookbook.windows_ad#121]
Hi,

I am using the windows_ad cookbook to **remove the user** from the ou here is the recipe I am using:

**# Delete user "Joe Smith" in the Test Users OU
windows_ad_user "Joe Smith" do
  action :delete
  domain_name "un.platform.dev"
  ou "Org/Services/Development/Users/Test Users"
end**

error i see ,

Synchronizing Cookbooks:
  - windows (5.1.3)
  - windows_ad (0.1.0)
  - ActiveDirectory_Automation (0.1.0)
Installing Cookbook Gems:
Compiling Cookbooks...
Converging 1 resources
Recipe: ActiveDirectory_Automation::Remove_User
  * windows_ad_user[Joe Smith] action delete[2019-04-04T17:04:59+00:00] INFO: Processing windows_ad_user[Joe Smith] acti
on delete (ActiveDirectory_Automation::Remove_User line 3)
[2019-04-04T17:05:00+00:00] INFO: windows_ad_user[delete Joe Smith]

    ================================================================================
    Error executing action `delete` on resource 'windows_ad_user[Joe Smith]'
    ================================================================================

    RuntimeError
    ------------
    Failed to execute command.
    STDOUT:
    STDERR: dsrm failed:Value for 'Target object for this command' has incorrect format.
    type dsrm /? for help.

    Cookbook Trace:
    ---------------
    c:/chef/cache/cookbooks/windows_ad/libraries/cmd_helper.rb:41:in `shell_out'
    c:/chef/cache/cookbooks/windows_ad/providers/user.rb:94:in `block in class_from_file'

    Resource Declaration:
    ---------------------
    # In c:/chef/cache/cookbooks/ActiveDirectory_Automation/recipes/Remove_User.rb

      3: windows_ad_user "Joe Smith" do
      4:   action :delete
      5:   domain_name "un.platform.dev"
      6:   ou "Org/Services/Development/Users/Test Users"
      7: end

    Compiled Resource:
    ------------------
    # Declared in c:/chef/cache/cookbooks/ActiveDirectory_Automation/recipes/Remove_User.rb:3:in `from_file'

    windows_ad_user("Joe Smith") do
      action [:delete]
      default_guard_interpreter :default
      declared_type :windows_ad_user
      cookbook_name "ActiveDirectory_Automation"
      recipe_name "Remove_User"
      domain_name "un.platform.dev"
      ou "org/Services/Development/Users/Test Users"
    end

    System Info:
    ------------
    chef_version=13.8.5
    platform=windows
    platform_version=6.3.9600
    ruby=ruby 2.4.3p205 (2017-12-14 revision 61247) [x64-mingw32]
    program_name=C:/opscode/chefdk/bin/chef-client
    executable=C:/opscode/chefdk/bin/chef-client

[2019-04-04T17:05:01+00:00] INFO: Running queued delayed notifications before re-raising exception

Running handlers:
[2019-04-04T17:05:01+00:00] ERROR: Running exception handlers
Running handlers complete
[2019-04-04T17:05:01+00:00] ERROR: Exception handlers complete
Chef Client failed. 0 resources updated in 08 seconds
[2019-04-04T17:05:01+00:00] INFO: Sending resource update report (run-id: 6f35727a-a2f5-4a9c-aae1-6e5074b53ac1)
[2019-04-04T17:05:01+00:00] FATAL: Stacktrace dumped to c:/chef/cache/chef-stacktrace.out
[2019-04-04T17:05:01+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2019-04-04T17:05:01+00:00] FATAL: RuntimeError: windows_ad_user[Joe Smith] (ActiveDirectory_Automation::Remove_User lin
e 3) had an error: RuntimeError: Failed to execute command.
STDOUT:
STDERR: dsrm failed:Value for 'Target object for this command' has incorrect format.
type dsrm /? for help.

Same error with **remove Group frm the OU.** Pasting recipe here :::

**# Add user "Joe Smith" in the Users OU to group "Admins" in OU "AD/Groups"
windows_ad_group_member 'Joe Smith' do
  action :remove
  group_name  'demo'
  domain_name 'un.platform.dev'
  user_ou 'Org/Services/Development/Users/Test Users'
  group_ou 'Org/Services/Development/Users'
end**

But I am **able to add USER and GrROUP succesfully** to AD using this same  cookbook.

Please help me out!

**Comment by derekgroh** [comment]
Any reason to not be using the latest version

**Comment by saivv** [comment]
Sorry not sure how that happend but now I am using the windows_ad  0.6.2 still it failed :(

Here you go the error part ::


Synchronizing Cookbooks:
  - windows (5.1.3)
  - ActiveDirectory_Automation (0.1.0)
[2019-04-04T18:37:17+00:00] INFO: Storing updated cookbooks/windows_ad/metadata.rb in the cache.
  - windows_ad (0.6.2)
Installing Cookbook Gems:
Compiling Cookbooks...
Converging 1 resources
Recipe: ActiveDirectory_Automation::Remove_User
  * windows_ad_user[Joe Smith] action delete[2019-04-04T18:37:18+00:00] INFO: Processing windows_ad_user[Joe Smith] acti
on delete (ActiveDirectory_Automation::Remove_User line 3)
[2019-04-04T18:37:18+00:00] INFO: windows_ad_user[delete Joe Smith]


    ================================================================================
    Error executing action `delete` on resource 'windows_ad_user[Joe Smith]'
    ================================================================================

    RuntimeError
    ------------
    Failed to execute command.
    STDOUT:
    STDERR: dsrm failed:Value for 'Target object for this command' has incorrect format.
    type dsrm /? for help.

    Cookbook Trace:
    ---------------
    c:/chef/cache/cookbooks/windows_ad/libraries/cmd_helper.rb:41:in `shell_out'
    c:/chef/cache/cookbooks/windows_ad/providers/user.rb:94:in `block in class_from_file'

    Resource Declaration:
    ---------------------
    # In c:/chef/cache/cookbooks/ActiveDirectory_Automation/recipes/Remove_User.rb

      3: windows_ad_user "Joe Smith" do
      4:   action :delete
      5:   domain_name "un.platform.dev"
      6:   ou "Org/Services/Development/Users/Test Users"
      7: end

    Compiled Resource:
    ------------------
    # Declared in c:/chef/cache/cookbooks/ActiveDirectory_Automation/recipes/Remove_User.rb:3:in `from_file'

    windows_ad_user("Joe Smith") do
      action [:delete]
      default_guard_interpreter :default
      declared_type :windows_ad_user
      cookbook_name "ActiveDirectory_Automation"
      recipe_name "Remove_User"
      domain_name "un.platform.dev"
      ou "Org/Services/Development/Users/Test Users"
    end

    System Info:
    ------------
    chef_version=13.8.5
    platform=windows
    platform_version=6.3.9600
    ruby=ruby 2.4.3p205 (2017-12-14 revision 61247) [x64-mingw32]
    program_name=C:/opscode/chefdk/bin/chef-client
    executable=C:/opscode/chefdk/bin/chef-client

[2019-04-04T18:37:19+00:00] INFO: Running queued delayed notifications before re-raising exception

Running handlers:
[2019-04-04T18:37:19+00:00] ERROR: Running exception handlers
Running handlers complete
[2019-04-04T18:37:19+00:00] ERROR: Exception handlers complete
Chef Client failed. 0 resources updated in 08 seconds
[2019-04-04T18:37:19+00:00] INFO: Sending resource update report (run-id: ad0ab0cf-9451-4cf7-bfad-f4b55f10060c)
[2019-04-04T18:37:19+00:00] FATAL: Stacktrace dumped to c:/chef/cache/chef-stacktrace.out
[2019-04-04T18:37:19+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2019-04-04T18:37:19+00:00] FATAL: RuntimeError: windows_ad_user[Joe Smith] (ActiveDirectory_Automation::Remove_User lin
e 3) had an error: RuntimeError: Failed to execute command.
STDOUT:
STDERR: dsrm failed:Value for 'Target object for this command' has incorrect format.
type dsrm /? for help.

**Comment by derekgroh** [comment]
I'm receiving the same error on the latest chef-client, appears to be an issue with the cmd_helper not resolving the DN correctly to delete the object.

**Comment by saivv** [comment]
Okay ! Do you know what can we do there as of now to make it work or can you update me when you are able to resolve this please. Thanks in advance :)

**Comment by derekgroh** [comment]
From what I'm seeing, likely not. It should be able to accept the full DN, but the way the helper is written I doubt it will pass through correctly.

If you want a true work around, run a powershell_script command for `dsrm "DN" -noprompt` to remove the object (this will work for any object, group, user, etc.)

**Comment by derekgroh** [comment]
@saivv try https://github.com/TAMUArch/cookbook.windows_ad/tree/feature/issue121 and see if that resolves the issue.

**Comment by saivv** [comment]
thanks it worked now I am able to remove it.

**Comment by saivv** [comment]
But for removing Group From Ou I still see this error :

Synchronizing Cookbooks:
  - windows (5.1.3)
  - windows_ad (0.6.3)
  - ActiveDirectory_Automation (0.1.0)
Installing Cookbook Gems:
Compiling Cookbooks...
Converging 1 resources
Recipe: ActiveDirectory_Automation::Remove_Group
  * windows_ad_group[Chef Teamtest] action delete[2019-04-08T18:42:48+00:00] INFO: Processing windows_ad_group[Chef Team
test] action delete (ActiveDirectory_Automation::Remove_Group line 2)
[2019-04-08T18:42:49+00:00] INFO: windows_ad_group[delete Chef Teamtest]


    ================================================================================
    Error executing action `delete` on resource 'windows_ad_group[Chef Teamtest]'
    ================================================================================

    RuntimeError
    ------------
    Failed to execute command.
    STDOUT:
    STDERR: dsrm failed:Value for 'Target object for this command' has incorrect format.
    type dsrm /? for help.

    Cookbook Trace:
    ---------------
    c:/chef/cache/cookbooks/windows_ad/libraries/cmd_helper.rb:41:in `shell_out'
    c:/chef/cache/cookbooks/windows_ad/providers/group.rb:94:in `block in class_from_file'

    Resource Declaration:
    ---------------------
    # In c:/chef/cache/cookbooks/ActiveDirectory_Automation/recipes/Remove_Group.rb

      2: windows_ad_group "Chef Teamtest" do
      3:   action :delete
      4:   domain_name "un.platform.dev"
      5:   ou "Services/Development/Users"
      6: end

    Compiled Resource:
    ------------------
    # Declared in c:/chef/cache/cookbooks/ActiveDirectory_Automation/recipes/Remove_Group.rb:2:in `from_file'

    windows_ad_group("Chef Teamtest") do
      action [:delete]
      default_guard_interpreter :default
      declared_type :windows_ad_group
      cookbook_name "ActiveDirectory_Automation"
      recipe_name "Remove_Group"
      domain_name "un.platform.dev"
      ou "Services/Development/Users"
    end

    System Info:
    ------------
    chef_version=13.8.5
    platform=windows
    platform_version=6.3.9600
    ruby=ruby 2.4.3p205 (2017-12-14 revision 61247) [x64-mingw32]
    program_name=C:/opscode/chefdk/bin/chef-client
    executable=C:/opscode/chefdk/bin/chef-client

[2019-04-08T18:42:49+00:00] INFO: Running queued delayed notifications before re-raising exception

Running handlers:
[2019-04-08T18:42:49+00:00] ERROR: Running exception handlers
Running handlers complete
[2019-04-08T18:42:49+00:00] ERROR: Exception handlers complete
Chef Client failed. 0 resources updated in 08 seconds
[2019-04-08T18:42:49+00:00] INFO: Sending resource update report (run-id: 3d381a1d-5a07-485d-8aa3-ed1d61b2a1c8)
[2019-04-08T18:42:49+00:00] FATAL: Stacktrace dumped to c:/chef/cache/chef-stacktrace.out
[2019-04-08T18:42:49+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2019-04-08T18:42:49+00:00] FATAL: RuntimeError: windows_ad_group[Chef Teamtest] (ActiveDirectory_Automation::Remove_Gro
up line 2) had an error: RuntimeError: Failed to execute command.
STDOUT:
STDERR: dsrm failed:Value for 'Target object for this command' has incorrect format.
type dsrm /? for help.

**Comment by derekgroh** [comment]
@saivv Add the escape for spaces in the OU for all the providers. Let me know if you see any other bugs.

**Comment by derekgroh** [comment]
You originally tried the OU path: `org/Services/Development/Users/Test Users`, which has a space so the provider was failing out because the DN was not double quoted.

Your latest OU path `Services/Development/Users` shouldn't have an issue, but the name has a space, which should be corrected by the same fix.

If you are still having issues, send me a PM on slack and we can try to work the issue.

**Comment by Techcadia** [comment]
@derekgroh Can we get this branch merged and a new version cut. I have a build dep on the windows version and this issue would solve it.

**Comment by derekgroh** [comment]
@Techcadia I'd like to finish linting and update the docs before updating supermarket, but I've prereleased the version here.

**Comment by derekgroh** [comment]
@saivv I'll keep this issue open for a while longer as I know you're still working through getting it working, let me know if you have any other questions.

**Comment by derekgroh** [comment]
We're taking some effort to clean up older issues for this repository. Please reply if you still wish for this to be worked on.
