### ISSUE TITLE
Issues with Custom Resource when Using Chef-Client v16

### ISSUE THREAD

**Issue by truonart** [TAMUArch/cookbook.windows_ad#126]
### Cookbook version
0.7.1

### Chef-client version
16.1.16

### Platform Details
ec2

### Scenario:
When using this custom resource I run into errors telling me I need the include domain_user property. This shouldn't be the case because this is a forest creation. 

windows_ad_domain domain_name do
  type 'forest'
  safe_mode_pass safe_mode_password
  restart true
  action :create
end

### Steps to Reproduce:
Update to Chef client to version 16 and test windows_ad_domain resource. 

### Expected Result:
We expect that the resource should be able to converge properly on a system and that we should have a forest created. 

### Actual Result:
When converging this resource on a system in Ec2, we receive this error. 
         * windows_ad_domain[test.net] action create
           ================================================================================
           Error executing action `create` on resource 'windows_ad_domain[test.net]'
           ================================================================================
           Chef::Exceptions::ValidationFailed
           ----------------------------------
           domain_user is a required property

### Additional Background Info:
This same resource with its current parameters was previously working on Chef Client`15`. After upgrading to chef-client v16 and chef workstation 20.6.62 the resource errors out. 

### Hypothesis/ Recommendation
We believe this is due to the updates done in Chef v16 
https://docs.chef.io/release_notes/#breaking-change-in-resources

There in the link, it recommends that a `provides` line gets added to the custom resources to support Chef v16

**Comment by mhincapie** [comment]
We are having exactly the same issue. Thank you @truonart for posting it. We hope its something simple that it can be updated.

We tried it with Chef 14 and Chef 15 and no issues.

**Comment by derekgroh** [comment]
Thanks for reporting this, it is indeed a simple fix. This should be available on supermarket later today.

**Comment by derekgroh** [comment]
@truonart Although the issue you reported is valid, it is because of incorrect usage of the resource.

* domain_user: User account to join the domain or to create a domain controller. **Required**: for `:create` except on `type` `forest` on windows 2012 and above.
* domain_pass: User password to join the domain or to create a domain controller. **Required**: for `:create` except on `type` `forest` on windows 2012 and above.

Admittedly, this is confusing, as the property is listed as required to cover the case that it is not a forest.

You will need to provide your resource as follows:
```ruby
windows_ad_domain 'test.net' do
  type 'forest'
  safe_mode_pass safe_mode_password
  domain_user 'administrator'
  domain_pass 'Passw0rd'
  restart true
  action :create
end
```
Where `domain_user` and `domain_pass` would be the values for the local administrator account for the system.

**Comment by mhincapie** [comment]
Thank you @derekgroh for the fast reply and solution. We experience the issue with a Windows 2016 and Chef Client 16. Per the instructions above we have been using the following code in Chef 14 and Chef 15 and has been working without adding the properties `domain_user` and `domain_pass`

```ruby
windows_ad_domain domain_name do
  type 'forest'
  safe_mode_pass safe_mode_password
  restart true
  action :create
end
```

Should we start using that from now on? or not necessary?

**Comment by truonart** [comment]
Hey @derekgroh, your suggestion fixed my issue. Thanks for the help and quick reply.
