### ISSUE TITLE
Weak password does not fail converge

### ISSUE THREAD

**Issue by rreilly-edr** [TAMUArch/cookbook.windows_ad#129]
### Cookbook version
0.7.2

### Chef-client version
16.6.4

### Platform Details
AWS/windows 2019 core

### Scenario:
create forest/domain

### Steps to Reproduce:
set a weak password

### Expected Result:
chef should exit with the error from the install

### Actual Result:
the chef run completes successfully with no error but I logged onto the machine and the domain has not been created. I ran chef in debug mode to get the command it was running and ran it manually but it fails complaining of a weak password. I fixed the password and the creation completed successfully. The chef run should definitely fail as the resource is failing but it is exiting properly.

this was the run with weak password no errors also the domain was not created.
```
Recipe: activedirectory::default
         * windows_ad_domain[prod.xx.lan] action create
           * powershell_script[create_domain_prod.xx.lan] action run
             - execute "C:\Windows\system32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NonInteractive -NoProfile -ExecutionPolicy Bypass -InputFormat None  -File "C:/Users/ADMINI~1/AppData/Local/Temp/chef-script20201022-2524-1u59s5o.ps1"
       
       
       Running handlers:
       Running handlers complete
       Chef Infra Client finished, 2/20 resources updated in 40 seconds
       Downloading files from <default-windows-2019-core>
       Finished converging <default-windows-2019-core> (1m16.99s).
```

**Comment by derekgroh** [comment]
What was the exit code of the command you manually ran? 

If this was `[0, 1, 2, 3, 4]`, then the chef resource would report success.

**Comment by rreilly-edr** [comment]
I will have to run the test again and see what it is exiting with.

**Comment by rreilly-edr** [comment]
stranger part, is it still executes with out error but is not actually creating the forest, again i take the command that would have been used, execute it and it creates the forest no errors. I will have to add in some debugging see if I can figure out what is going on.

**Comment by derekgroh** [comment]
You can view this output by setting Chef-client in debug mode. 

`provisioner:
  name: chef_zero
  chef_license: accept-no-persist
  product_name: chef
  log_level: debug`

The powershell command executes successfully, but the command logs the following warning which results in aborting the creation of the domain:
`Verification of prerequisites for Domain Controller promotion failed. The Directory Services Restore Mode password does not meet the password complexity requirements of the password policy. Strong passwords require a combination of uppercase and lowercase letters, numbers, and symbols. Supply a stronger password.`

This is noted in the Microsoft documentation: https://docs.microsoft.com/en-us/powershell/module/addsdeployment/install-addsdomain?view=win10-psa 
`You must supply a password that meets the password complexity rules of the domain and the password cannot be blank.`

By default those requirements are outlined here:
https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/password-must-meet-complexity-requirements

The README.md can be updated to highlight this more clearly, but this is not a bug with the cookbook and more so a limitation of the requirements for using the `Install-ADDSDomain` command and ADDS's unique requirements.
