### ISSUE TITLE
Managing AD objects during "normal" chef-run

### ISSUE THREAD

**Issue by miguelaferreira** [TAMUArch/cookbook.windows_ad#35]
Hi,

This cookbook works fine to create and mange AD objects as long as the user running chef-client has domain admin rights.
However, in the "normal" chef-client runs  (i.e. started by the timer) the user that runs typically has read access to AD.

The obvious solution seem to be raising the AD privileges of the user running chef-client, but that might trigger some alarms from security policies, etc. Another one would be, temporarily raising privileges just for this one thing, a sort of windows equivalent to the linux `sudo` command.

Has anyone using this cookbook thought of this issue? Any ideas on how to fix it?

**Comment by lolindirfalasion** [comment]
Pull request merged.
