### ISSUE TITLE
Setting DNS before joining domain

### ISSUE THREAD

**Issue by miguelaferreira** [TAMUArch/cookbook.windows_ad#37]
When joining a domain, unless there is external DNS setup, one needs to update the DNS records on the box in order for it to connect to the DC.

Any ideas on how to achieve this with chef/ruby?

**Comment by lolindirfalasion** [comment]
Before installing ADDS? Modify the hosts file or install DNS before ADDS.  I feel an easier solution would be to provide the correct networking information either via DHCP or to statically set the DNS server

**Comment by miguelaferreira** [comment]
@lolindirfalasion I've tried setting up a hosts file on the machine that joins the domain, but what do I put in the host name?

I mean, if my domain is called `test.local` should I map that to the IP of the domain controller machine?

**Comment by lolindirfalasion** [comment]
# localhost name resolution is handled within DNS itself.
# 127.0.0.1       localhost
# :1                   localhost
10.0.0.1            test.local

Should work for you.  To test it, open a command prompt and do ipconfig /flushdns then do an nslookup on the ip and domain name to make sure it is resolving correctly.

**Comment by miguelaferreira** [comment]
So I did that. hosts file looks like this:
```
#
#...
#

192.168.56.5    test.local
```

I can ping the host:
```
PS C:\Windows\System32\drivers\etc> ping test.local

Pinging test.local [192.168.56.5] with 32 bytes of data:
Reply from 192.168.56.5: bytes=32 time<1ms TTL=128

Ping statistics for 192.168.56.5:
    Packets: Sent = 1, Received = 1, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 0ms, Maximum = 0ms, Average = 0ms
```

But the DNS lookup does not work:
```
PS C:\Windows\System32\drivers\etc> nslookup test.local
Server:  UnKnown
Address:  10.0.2.3

*** UnKnown can't find test.local: Non-existent domain
```

The IP addresses of the domain control are:
```
10.0.2.15
196.168.56.5
```

**Comment by lolindirfalasion** [comment]
Looks like you're in a private network trying to find another private network.  Vagrant?

**Comment by miguelaferreira** [comment]
Yes it is a private network and both boxes are in that same network.

Vagrant file snippet:
```ruby
config.vm.network 'private_network', ip: options['ip'], virtualbox__intnet: 'windows_ad'
```

**Comment by lolindirfalasion** [comment]
Come join me here, we can discuss it: http://www.hipchat.com/g8eZZzR15

**Comment by alex-williams** [comment]
Hiya, I'm having a problem getting this to join a domain, with Windows 2012 (Not R2). Both the member server and the DC are 2012.

I've run the code from the resource directly in powershell and it joins the domain, reboots the server and all is well, but for some reason, if I use the recipe I get the following output, every time (I've removed passwords and the actual domain etc..

[2015-02-05T16:27:13+00:00] INFO: Processing powershell_script[join_mydomain] action run (C:/chef/cache/cookbooks/windows_ad/providers/domain.rb line 92)

================================================================================
Error executing action `run` on resource 'powershell_script[join_mydomain]'
================================================================================

Mixlib::ShellOut::ShellCommandFailed
------------------------------------
Expected process to exit with [0], but received '1'
---- Begin output of "powershell.exe" -NoLogo -NonInteractive -NoProfile -ExecutionPolicy Unrestricted -InputFormat None -File "C:/Windows/Temp/chef-script20150205-2788-8r8gm.ps1" ----
STDOUT: 
STDERR: Computer 'WIN-GRE2AI61M0C' failed to join domain 'my.domain.com' from its current workgroup 'WORKGROUP' with following error message: Unable to update the password. The value provided as the current password is incorrect.
---- End output of "powershell.exe" -NoLogo -NonInteractive -NoProfile -ExecutionPolicy Unrestricted -InputFormat None -File "C:/Windows/Temp/chef-script20150205-2788-8r8gm.ps1" ----
Ran "powershell.exe" -NoLogo -NonInteractive -NoProfile -ExecutionPolicy Unrestricted -InputFormat None -File "C:/Windows/Temp/chef-script20150205-2788-8r8gm.ps1" returned 1

Resource Declaration:
---------------------
# In C:/chef/cache/cookbooks/windows_ad/providers/domain.rb

 92:       powershell_script "join_#{new_resource.name}" do
 93:         if node[:os_version] >= "6.2"
 94:           code <<-EOH
 95:             $secpasswd = ConvertTo-SecureString '#{new_resource.domain_pass}' -AsPlainText -Force
 96:             $mycreds = New-Object System.Management.Automation.PSCredential  ('#{new_resource.domain_user}', $secpasswd)
 97:             Add-Computer -DomainName #{new_resource.name} -Credential $mycreds -Force:$true -Restart
 98:           EOH
 99:         else
100:           code "netdom join #{node[:hostname]} /d #{new_resource.name} /ud:#{new_resource.domain_user} /pd:#{new_resource.domain_pass} /reboot"
101:         end
102:       end

Compiled Resource:
------------------
# Declared in C:/chef/cache/cookbooks/windows_ad/providers/domain.rb:92:in `block in class_from_file'

powershell_script("join_mydomain") do
  action "run"
  retries 0
  retry_delay 2
  default_guard_interpreter :powershell_script
  command "\"powershell.exe\" -NoLogo -NonInteractive -NoProfile -ExecutionPolicy Unrestricted -InputFormat None -File \"C:/Windows/Temp/chef-script20150205-2788-8r8gm.ps1\""
  backup 5
  returns 0
  code "            $secpasswd = ConvertTo-SecureString 'MySecurePassword' -AsPlainText -Force\n            $mycreds = New-Object System.Management.Automation.PSCredential  ('sup_chef', $secpasswd)\n            Add-Computer -DomainName my.domain.com -Credential $mycreds -Force:$true -Restart\n"
  interpreter "powershell.exe"
  declared_type :powershell_script
  cookbook_name "windows_ad"
end

[2015-02-05T16:27:15+00:00] INFO: Running queued delayed notifications before re-raising exception
[2015-02-05T16:27:15+00:00] ERROR: Running exception handlers
[2015-02-05T16:27:15+00:00] ERROR: Exception handlers complete
[2015-02-05T16:27:15+00:00] FATAL: Stacktrace dumped to C:/chef/cache/chef-stacktrace.out
[2015-02-05T16:27:15+00:00] FATAL: Mixlib::ShellOut::ShellCommandFailed: powershell_script[join_mydomain] (C:/chef/cache/cookbooks/windows_ad/providers/domain.rb line 92) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of "powershell.exe" -NoLogo -NonInteractive -NoProfile -ExecutionPolicy Unrestricted -InputFormat None -File "C:/Windows/Temp/chef-script20150205-2788-8r8gm.ps1" ----
STDOUT: 
STDERR: Computer 'WIN-GRE2AI61M0C' failed to join domain 'my.domain.com' from its current workgroup 'WORKGROUP' with following error message: Unable to update the password. The value provided as the current password is incorrect.
---- End output of "powershell.exe" -NoLogo -NonInteractive -NoProfile -ExecutionPolicy Unrestricted -InputFormat None -File "C:/Windows/Temp/chef-script20150205-2788-8r8gm.ps1" ----
Ran "powershell.exe" -NoLogo -NonInteractive -NoProfile -ExecutionPolicy Unrestricted -InputFormat None -File "C:/Windows/Temp/chef-script20150205-2788-8r8gm.ps1" returned 1

Can you help?

**Comment by miguelaferreira** [comment]
So, in the end I had to set DNS in order to resolve the domain name to the IP of the DC.
I did it like this:
```ruby
powershell_script 'set DNS servers to resolve domain name' do
  code "Set-DNSClientServerAddress -interfaceIndex 12 -ServerAddresses (\"#{dc_ip}\",\"8.8.8.8\")"
end
```
I will improve it to first scan for NICs and set the index(es) accordingly.

**Comment by lolindirfalasion** [comment]
I'll continue to see if I can find a solution for vagrant / virtualbox as it would be useful for testing, but likely won't include anything in the cookbook as it is a virtual box limitation

**Comment by lolindirfalasion** [comment]
@miguelaferreira I'm going to close this issue, but it is a good info to be aware of this limitation with vagrant/virtualbox when testing.

**Comment by miguelaferreira** [comment]
Just for furture reference:

```ruby
WindowsHelper.nic_interface_indexes.each do |index|
  powershell_script "set DNS servers for NIC #{index}" do
    code "Set-DNSClientServerAddress -interfaceIndex #{index} -ServerAddresses (\"#{dc_ip}\",\"8.8.8.8\")"
  end
end
```

```ruby
class WindowsHelper
  if RUBY_PLATFORM =~ /mswin|mingw32|windows/
    require 'win32ole'
    @@wmi = WIN32OLE.connect("winmgmts://")
  end

  def self.nic_interface_indexes
    indexes = []
    nics = @@wmi.ExecQuery("Select * from Win32_NetworkAdapter Where NetConnectionStatus = 2")
    nics.each do |nic|
      indexes << nic.interfaceindex
    end
    indexes
  end
end
```

**Comment by alex-williams** [comment]
This is very relevant for AWS usage as well, so I like this. I currently do much the same thing in my powershell bootstrap script, before running chef.

**Comment by miguelaferreira** [comment]
@alex-williams good to know you like it. I didn't go through the trouble to make it idempotent since I only use it for testing this cookbook (and others that require a windows domain). However I would suggest to add a conditional clause to the powershell_script resource to achieve idempotency.
