### ISSUE TITLE
Issue with joining the domain on Windows 2012

### ISSUE THREAD

**Issue by alex-williams** [TAMUArch/cookbook.windows_ad#38]
Hiya, I'm having a problem getting this to join a domain, with Windows 2012 (Not R2). Both the member server and the DC are 2012.

I've run the code from the resource directly in powershell and it joins the domain, reboots the server and all is well, but for some reason, if I use the recipe I get the following output, every time (I've removed passwords and the actual domain etc.)

[2015-02-05T16:27:13+00:00] INFO: Processing powershell_script[join_mydomain] action run (C:/chef/cache/cookbooks/windows_ad/providers/domain.rb line 92)

================================================================================
Error executing action `run` on resource 'powershell_script[join_mydomain]'
================================================================================

Mixlib::ShellOut::ShellCommandFailed
------------------------------------
Expected process to exit with [0], but received '1'
---- Begin output of "powershell.exe" -NoLogo -NonInteractive -NoProfile -ExecutionPolicy Unrestricted -InputFormat None -File "C:/Windows/Temp/chef-script20150205-2788-8r8gm.ps1" ----
STDOUT: 
STDERR: Computer 'WIN-GRE2AI61M0C' failed to join domain 'my.domain.com' from its current workgroup 'WORKGROUP' with following error message: Unable to update the password. The value provided as the current password is incorrect.
---- End output of "powershell.exe" -NoLogo -NonInteractive -NoProfile -ExecutionPolicy Unrestricted -InputFormat None -File "C:/Windows/Temp/chef-script20150205-2788-8r8gm.ps1" ----
Ran "powershell.exe" -NoLogo -NonInteractive -NoProfile -ExecutionPolicy Unrestricted -InputFormat None -File "C:/Windows/Temp/chef-script20150205-2788-8r8gm.ps1" returned 1

Resource Declaration:
---------------------
\# In C:/chef/cache/cookbooks/windows_ad/providers/domain.rb

 92:       powershell_script "join_#{new_resource.name}" do
 93:         if node[:os_version] >= "6.2"
 94:           code <<-EOH
 95:             $secpasswd = ConvertTo-SecureString '#{new_resource.domain_pass}' -AsPlainText -Force
 96:             $mycreds = New-Object System.Management.Automation.PSCredential  ('#{new_resource.domain_user}', $secpasswd)
 97:             Add-Computer -DomainName #{new_resource.name} -Credential $mycreds -Force:$true -Restart
 98:           EOH
 99:         else
100:           code "netdom join #{node[:hostname]} /d #{new_resource.name} /ud:#{new_resource.domain_user} /pd:#{new_resource.domain_pass} /reboot"
101:         end
102:       end

Compiled Resource:
------------------
# Declared in C:/chef/cache/cookbooks/windows_ad/providers/domain.rb:92:in `block in class_from_file'

powershell_script("join_mydomain") do
  action "run"
  retries 0
  retry_delay 2
  default_guard_interpreter :powershell_script
  command "\"powershell.exe\" -NoLogo -NonInteractive -NoProfile -ExecutionPolicy Unrestricted -InputFormat None -File \"C:/Windows/Temp/chef-script20150205-2788-8r8gm.ps1\""
  backup 5
  returns 0
  code "            $secpasswd = ConvertTo-SecureString 'MySecurePassword' -AsPlainText -Force\n            $mycreds = New-Object System.Management.Automation.PSCredential  ('sup_chef', $secpasswd)\n            Add-Computer -DomainName my.domain.com -Credential $mycreds -Force:$true -Restart\n"
  interpreter "powershell.exe"
  declared_type :powershell_script
  cookbook_name "windows_ad"
end

[2015-02-05T16:27:15+00:00] INFO: Running queued delayed notifications before re-raising exception
[2015-02-05T16:27:15+00:00] ERROR: Running exception handlers
[2015-02-05T16:27:15+00:00] ERROR: Exception handlers complete
[2015-02-05T16:27:15+00:00] FATAL: Stacktrace dumped to C:/chef/cache/chef-stacktrace.out
[2015-02-05T16:27:15+00:00] FATAL: Mixlib::ShellOut::ShellCommandFailed: powershell_script[join_mydomain] (C:/chef/cache/cookbooks/windows_ad/providers/domain.rb line 92) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of "powershell.exe" -NoLogo -NonInteractive -NoProfile -ExecutionPolicy Unrestricted -InputFormat None -File "C:/Windows/Temp/chef-script20150205-2788-8r8gm.ps1" ----
STDOUT: 
STDERR: Computer 'WIN-GRE2AI61M0C' failed to join domain 'my.domain.com' from its current workgroup 'WORKGROUP' with following error message: Unable to update the password. The value provided as the current password is incorrect.
---- End output of "powershell.exe" -NoLogo -NonInteractive -NoProfile -ExecutionPolicy Unrestricted -InputFormat None -File "C:/Windows/Temp/chef-script20150205-2788-8r8gm.ps1" ----
Ran "powershell.exe" -NoLogo -NonInteractive -NoProfile -ExecutionPolicy Unrestricted -InputFormat None -File "C:/Windows/Temp/chef-script20150205-2788-8r8gm.ps1" returned 1

Can you help? When I ran the code directly in powershell, I literally copy/pasted from this error, so the password is definitely not wrong. Obviously I've edited the password in this output, but can tell you it's alpha-numeric, with no abstract characters.

**Comment by lolindirfalasion** [comment]
@alex-williams The error you're getting is "Unable to update the password. The value provided as the current password is incorrect."  Try the following link for assistance: http://support.microsoft.com/kb/842715

**Comment by alex-williams** [comment]
Hi, the password is correct, as I said in the issue above, if I copy and paste the code, directly from the error, including the password, it works perfectly fine.

**Comment by lolindirfalasion** [comment]
@alex-williams Can you provide your recipe?

**Comment by alex-williams** [comment]
windows_ad_domain "my.domain.com" do
  action :join
  domain_pass "secretPassword"
  domain_user "sup_chef"
end

**Comment by alex-williams** [comment]
I don't know if you've had a chance to look at this, but it would appear the SYSTEM user that Chef runs under, is unable to join a domain. I'm currently trying something that might work around this. If I get anywhere, I'll let you know.

**Comment by lolindirfalasion** [comment]
@alex-williams Hmm I'm guessing that with https://github.com/TAMUArch/cookbook.windows_ad/pull/20 we probably should of had line 145 be ```ruby if node[:os_version] >= '6.2' ```

**Comment by lolindirfalasion** [comment]
@alex-williams I was able to run your recipe successfully in vagrant.  If you need further help ping me here and I'll see what I can help you with.

http://www.hipchat.com/g8eZZzR15

**Comment by galenemery** [comment]
Looking into this issue; there's several potential causes for the "error message: Unable to update the password. The value provided as the current password is incorrect."

Most of them have to do with network connectivity issues between the computer and DC.  Which should be ruled out if it can execute manually.

There was one mention that if the user you're attempting to use is not part of Local Users, that could cause issues.  So, it would be possible that the chef-client service, running as local system may cause an issue.  If you run chef-client manually from a prompt, does the issue reproduce there?

If not, then just change the user you run chef under, simplest way is to switch to a scheduled task.

Here's a link to an issue about that: https://github.com/chef/chef/issues/2861

**Comment by alex-williams** [comment]
It seems this was as simple as adding the domain, to the username in the recipe, thus:

windows_ad_domain "my.domain.com" do
action :join
domain_pass "secretPassword"
domain_user "domain\\sup_chef"
end

The domain was not needed for issuing the command manually on the command line, but it is from Chef for some reason. Probably relating to the use of the SYSTEM account, instead of the local Administrator account somehow.

**Comment by cixelsyd** [comment]
@alex-williams Thanks so much - I received this exact error when using this cookbook.  The readme should be updated to note that using domain_user "domain\\user" is necessary for domain joins.

**Comment by derekgroh** [comment]
@cixelsyd We're working on cleaning up the documentation and providers, if you you notice an inconsistency, please let us know.  Regarding the :required flag, the :domain provider has been the wrong place for :join and :unjoin for a long time. It will shortly be moved to the :computer provider.

**Comment by cixelsyd** [comment]
Makes sense.  I just worked through the logic in providers.rb and found some functional bugs there, too.


mobile
