### ISSUE TITLE
Support more containers

### ISSUE THREAD

**Issue by miguelaferreira** [TAMUArch/cookbook.windows_ad#40]
Currently the cookbook supports some AD containers (e.g. users).
But there a re more containers that are handy to use (e.g. Builtin, ForeignSecurityPrincipals, Managed Service Accounts).

I will work on the support for these containers.

Please let me know if there are already people working on this.

**Comment by lolindirfalasion** [comment]
Not that anyone has told me.  Our work with FSP is to add the object to a domain local group which creates the FSP, but support for those containers would be nice.

**Comment by miguelaferreira** [comment]
@lolindirfalasion could you please release a new version of the cookbook? I would like to freeze it and our policy does not allow me to freeze patched versions.
