### ISSUE TITLE
Error creating OU does not break chef-client run

### ISSUE THREAD

**Issue by miguelaferreira** [TAMUArch/cookbook.windows_ad#42]
In a chef-client run I saw an error saying "parent OU does not exists". That means chef-client tried to create an OU for which there was not a valid parent.
However, chef-client continued to run, instead of breaking.

I would expect the client to break, otherwise it will be harder to identify the root cause (a missing or not well defined AD object) of other failures further down the line.

Example error I saw:

```
  * windows_ad_ou[Service Accounts] action create (up to date)
  * windows_ad_ou[Users] action create (up to date)
  * windows_ad_ou[Groups] action create[2015-02-22T18:11:58+01:00] ERROR: The parent OU does not exist
 (up to date)
  * windows_ad_ou[AD] action create (up to date)
```

**Comment by miguelaferreira** [comment]
The problem is that the methods that check for the parent OU are not decomposing a nested out. That is, when the parent OU is something like "a/b", the provider will check for the existence of a DN that starts with "OU=a/b,...".

I will provide a patch that addresses this. The strategy will be to refactor the functionality that decomposes nested OUs into a separate method in the helper class, unit test that, and then reuse it in the OU provider.

**Comment by miguelaferreira** [comment]
My PR partly addresses this issue. It fixes the problem with nested OUs, but it does not break the chef-client run when there is an error.

I did not make that change because it is something that happens with all providers.
I'm in favour of breaking the client run when there is an error manipulating an AD object, this way it becomes more visible. But before I make such a crosscutting change I would like to know if other people think it is better to simply log the errors and move on.

**Comment by miguelaferreira** [comment]
@lolindirfalasion ping

Any thoughts on how to handle errors coming from the AD management tools?

**Comment by lolindirfalasion** [comment]
@miguelaferreira Why not code in a flag that would cause it to error if the individual wants it to do so, but by default log the error to console and continue the run?

**Comment by miguelaferreira** [comment]
Sounds like a plan :+1:
