### ISSUE TITLE
domain :join action is erroring if the domain exists instead of not exists

### ISSUE THREAD

**Issue by jhsubscribe** [TAMUArch/cookbook.windows_ad#62]
G'day All,

Thanks for another useful cookbook.   

Am I missing something obvious or should the following domain :join code say "!exists?"  (If so I guess most folks using this cookbook aren't using chef for the actual domain join).   

action :join do
  if exists?
    Chef::Log.error("The domain does not exist or was not reachable, please check your network settings")
    new_resource.updated_by_last_action(false)
  else

I'm happy to do a PR for this, I just wanted to check first.   Also, do you think the resource should probably error if you do domain :join and the domain doesn't exist or isn't contactable?  (and then users can override with ignore_failure true if they don't care)

**Comment by derekgroh** [comment]
That does seem backwards doesn't it? Hmm

**Comment by derekgroh** [comment]
@jhsubscribe If you want to do a PR that would be great.  

exists? and computer_exists? are both evaluating false during my testing, however manually running the commands is producing the desired results.  So there is clearly something wrong going on here.
