### ISSUE TITLE
Create forest/domain with options don't work

### ISSUE THREAD

**Issue by geerzo** [TAMUArch/cookbook.windows_ad#69]
Windows 2008

```
# Create Contoso.com forest with DNS, Win2008 R2 Operational Mode Windows Server 2008 R2
windows_ad_domain "contoso.com" do
  action :create
  type "forest"
  safe_mode_pass "Passw0rd"
  options ({ "domainlevel" => "4",
             "forestlevel" => "4",
             "InstallDNS" => "yes"
           })
end
```

The options aren't formatted correctly. In this case you wind up with "-forestlevel 4" on the shell command for dcpromo when it should be "-forestlevel:3". 

I suspect this has something to do with the warning at the beginning of the run of 

"ERROR: This version of Windows Server is currently unsupported beyond installing the required roles and features"

**Comment by derekgroh** [comment]
@geerzo Yep, just ran into this.

Sorta, we need to remove that message, we've been supporting Server 2008 for some time now, there are just some remaining bugs with integration.

Try this to work within the current framework:

windows_ad_domain "contoso.com" do
  action :create
  type "forest"
  safe_mode_pass "Passw0rd"
  options ({ "domainlevel" => "4",
                  "forestlevel" => "4",
                  "InstallDNS:yes" => nil
               })
end
