### ISSUE TITLE
Impossible to modify a user into OU which contains one space

### ISSUE THREAD

**Issue by odurgeau** [TAMUArch/cookbook.windows_ad#71]
When I try to modify a single user and I use an OU which contains one space in his name, I have an error like this : 
```
dsmod failed:Value for 'Target object for this command' has incorrect format.
```

I notice into LWRP create user, the DN identifier is surrounded with double quote whereas for modify action not.
```ruby
    cmd = "dsadd"
    cmd << " user "
    cmd << "\""
    cmd << dn
    cmd << "\""
```

```ruby
    cmd = "dsmod"
    cmd << " user "
    cmd << dn
```

**Comment by derekgroh** [comment]
@odurgeau Submit a pull request and I can merge it in.

**Comment by odurgeau** [comment]
The pull request has been created : #72

**Comment by derekgroh** [comment]
Merged, thanks!

**Comment by odurgeau** [comment]
Yw
Thx for this cookbook

**Comment by odurgeau** [comment]
Ultimately, the last commit on this file to remove one line used for surrounded the dn variable for "modify" user : bea632c4a3d50555ac92ab410548b0f297380ca8

Now :
```
 action :modify do
  if exists?
    cmd = 'dsmod'
    cmd << ' user '
    cmd << dn
    cmd << "\""
```
Instead of :
```
 action :modify do
  if exists?
    cmd = 'dsmod'
    cmd << ' user '
    cmd << "\""
    cmd << dn
    cmd << "\""
```
