### ISSUE TITLE
version 0.5.0, parameter issue when trying to join domain

### ISSUE THREAD

**Issue by christianTragesser** [TAMUArch/cookbook.windows_ad#82]
I'm attempting to join a Server 2012R2 host to our domain using the windows_ad_computer resource in a similar fashion to what I'm seeing in the README:

```
windows_ad_computer "#{node[:hostname]}" do
    action :join
    domain_pass "#{domain_user[:password]}"
    domain_user "#{domain_user[:user]}"
    domain_name "#{node[:cookbook][:ad_domain]}"
    ou "Application/Servers/datacenter"
    restart false
 end
```

When attempting to converge the node the chef-client run fails with the following error:

```
NoMethodError
       -------------
       undefined method `domain_pass' for Custom resource windows_ad_computer from cookbook windows_ad
```

I'm using Berkshelf to pull version 0.5.0 directly from GitHub(not using the Chef Supermarket version).

**Comment by christianTragesser** [comment]
I forked the repo, merged the 'fixes' branch and see the changes you're talking about regarding the resource.  However, when attempting to implement the changes I'm see the same error FWIW.  I'm not strong in Chef custom resources and providers but will continue to troubleshoot and see if I can contribute in terms of a PR.

**Comment by derekgroh** [comment]
The code is present in the prerelease, if you want to hop on the gitter I'm more than happy to help troubleshoot.

**Comment by christianTragesser** [comment]
So a correction to my previous statement.  I was getting the same error because I was still pulling the configs from the master branch courtesy of the Berksfile.lock.  The added domain_ attributes to the computer resource resolved the error I was previously getting.  I had to also add the restart attribute as a '[ TrueClass, FalseClass ]' type, then the `:join` action for the ad_window_computer resource worked for me.  I can submit a PR if you'd like or you could just add the restart attribute to the 'fixes' branch before merging and I think that custom resource will be in good shape.

**Comment by derekgroh** [comment]
@christianTragesser Good catch, edit submitted to fixes.  Let me know if you catch anything else that needs correcting.

**Comment by christianTragesser** [comment]
The current 'fixes' branch shows the restart attribute as type String; this does not work.  Has to be type '[ TrueClass, FalseClass ]' to used boolean values.

Currently the netdom query logic in the Computer provisioner does not appear to be working correctly in comparison to what I'm seeing when performing the commands manually.  Meaning, the current Computer provisioner logic for 'def exists?' returns "The domain does not exist or was not reachable, please check your network settings" which contrasts what I see when performing the same netdom query manually.

I'm also seeing an issue with the Computer provisioner as it assumes dsquery(Remote Server Administration Tools for Windows 10 or Active Directory Domain Services server role) is installed on the node.  I'm not liking dsquery being a dependency on any node I'd want to add to a domain.

I'm going to work further on the Provider then submit a PR once I get it working.

**Comment by derekgroh** [comment]
@christianTragesser Sounds good.  I was seeing an issue with the provider as well, but mine turned out to be the wrong password.  Performing some more tests across Win2008r2 and Win2012r2 now.

**Comment by christianTragesser** [comment]
Weird....regarding the netdom query logic I had the same issue.  I was incorrectly pulling credentials from a data bag.  Sorry for the confusion on that, I'm testing while refactoring a pretty gaudy cookbook.

So are you installing dsquery on every host you're wanting to join to a domain when using this cookbook?  I'm not seeing how the join action works w/o it.

**Comment by derekgroh** [comment]
No, during the development of this cookbook, netdom was found to be the lowest most common method to detect a domain.

Another method should be found to replace that method, but at current I have not seen any better command.  Of the workstations that were tested, they all have RSAT installed so netdom would have been installed.

An alternative method would be to change the code to attempt the domain and allow failure, catch the error and allow the option to stop the chef run or continue with the error.

**Comment by derekgroh** [comment]
@christianTragesser The other option would be to utilize https://github.com/NetDocuments/ad-join-cookbook/ work to enhance the provider.  They've already approved collaboration.

What are your thoughts on checking to see if the domain exists or not?

**Comment by derekgroh** [comment]
We're taking some effort to clean up older issues for this repository.

This feature has been addressed by Chef with the resource: https://docs.chef.io/resource_windows_ad_join.html
