### ISSUE TITLE
Version 0.4.5 on supermarket readme doesnt match implementation

### ISSUE THREAD

**Issue by johnsmyth** [TAMUArch/cookbook.windows_ad#83]
The 0.4.5 version of this cookbook that is uploaded to the Chef supermarket does not contain the :join and :unjoin actions for the computer resource as specified in the README of that version.  Also, the version 0.4.5 on supermarket does not appear to be the same as the commit that is tagged 'v0.4.5' here (which does have those actions in the resource btw).

**Comment by derekgroh** [comment]
@johnsmyth please use the fixes branch.

V0.4.5 shouldn't be used for the number of bugs identified

**Comment by derekgroh** [comment]
@johnsmyth Released 0.5.1, please address any concerns you have with that version.
