### ISSUE TITLE
Creating users fails with dsquery: No value specified for name

### ISSUE THREAD

**Issue by angelomk** [TAMUArch/cookbook.windows_ad#85]
Hi guys,

I am trying to utilize your cookbook for domain users creation but I've hit an issue: 

`addns1 Error executing action `create` on resource 'windows_ad_user[servicesql]'`
`addns1 RuntimeError`
`addns1 STDOUT:`
`addns1 STDERR:`
`addns1              dsquery failed:No value specified for 'name'.`
`addns1 Cookbook Trace:`
`addns1 c:/chef/cache/cookbooks/windows_ad/libraries/cmd_helper.rb:43:in shell_out'`
`addns1 c:/chef/cache/cookbooks/windows_ad/providers/user.rb:127:in exists?'`
`addns1 c:/chef/cache/cookbooks/windows_ad/providers/user.rb:29:in block in class_from_file'`

This is the resource used in the recipe:

`windows_ad_user "servicesql" do`
`  action :create`
`  domain_name "addns.local"`
`  ou "Users"`
`  options ({ "samid" => "servicesql",`
`        "upn" => "servicesql@addns.local",`
`         "fn" => "Service",`
`         "ln" => "SQL",`
`         "display" => "Service, SQL",`
`         "disabled" => "no",`
`         "desc" => "service account for SQL",`
`         "pwd" => "Something"`
`      })`
`end`

I also tried the example presented with Joe Smith with/without specifying _name_ as attribute parameter.
Deletion of users already in the OU gives the same error as well.

Am I missing some definition in the resource?

Thanks,
Angel

**Comment by derekgroh** [comment]
@angelomk Looking into this.

**Comment by achalupa74** [comment]
I'm seeing the exact same issue.  I've tried the 2 most recent versions (0.5.1 and 0.4.5) and they both seem to exhibit this dsquery problem?

**Comment by achalupa74** [comment]
I've found the issue.the dsquery command (in .../providers/users.rb) on this line of code was split across two lines:

    contact = CmdHelper.shell_out("dsquery contact 
                                  -name \"#{new_resource.name}\"", cmd_user,
                                  cmd_pass, cmd_domain)

removin the newline in the string command "dsquery contact -name \"#{new_resource.name}\""" solves the problem.

**Comment by derekgroh** [comment]
@achalupa74 That's a rubocop edit.  Let me check the other providers and get something pushed later today.

**Comment by derekgroh** [comment]
@achalupa74 Here is the updated branch.  

https://github.com/TAMUArch/cookbook.windows_ad/tree/issue_85

I'm not able to perform all the tests on the branch right now, but will try to get to it over the next day or two.  Let me know if that works for you or if more edits are required.

**Comment by angelomk** [comment]
@derekgroh I just did a quick test with "issue_85" branch and I can confirm that users creation works fine now @achalupa74

Looking fwd for the merge, thanks!

**Comment by deancsmith** [comment]
I was having issues creating an OU and Users with 0.51.

Switching to the issue_85 tag made Chef flawlessly for me.

This was on 2008r2 and only creating a domain, two OUs and two users.

**Comment by derekgroh** [comment]
Merged, let me know if you discover any other bugs!

-Thanks
