### ISSUE TITLE
Joining Linux or Unix hosts

### ISSUE THREAD

**Issue by aktarali** [TAMUArch/cookbook.windows_ad#91]
Hi,

Is there any plans to add the functionality to join non Windows environments to ad?

Regards

**Comment by derekgroh** [comment]
@aktarali Unless I'm missing something that is universially provided, *nix joining to and AD domain is handled by a 3rd party software suite (Centrify, PBIS, etc.).

As such, the best option would be a wrapper cookbook to call that community cookbook if one exists.

If you can provide more information how you are currently doing this, I'm open to exploring the request.

**Comment by aktarali** [comment]
Hi,

Appreciate you considering to look into ways of doing this.

The most common and acceptable was is using samba...
https://www.samba.org/samba/docs/man/Samba-HOWTO-Collection/domain-member.html

Cheers
Ali

**Comment by aktarali** [comment]
Another guide...
https://devopslab.wordpress.com/2014/04/10/configure-samba-with-active-directory-integration-centos-6/

**Comment by derekgroh** [comment]
@aktarali Does this meet your needs? https://github.com/Webtrends/ad-auth

I can start looking into it using samba if that doesn't meet your needs.

**Comment by aktarali** [comment]
I've seen this bud, I'll give this a try

**Comment by Spechal** [comment]
SSSD is another common authentication mechanism and goes back to use another or wrapper cookbook ... https://supermarket.chef.io/cookbooks/sssd_ad

**Comment by derekgroh** [comment]
We're taking some effort to clean up older issues for this repository.

If you still have a need for this feature, please submit the request to the Chef repository for resource windows_ad_join (https://github.com/chef/chef/blob/master/lib/chef/resource/windows_ad_join.rb) as this cookbook is no longer going to handle duplicating an existing resource.
