### ISSUE TITLE
cmd attributes appear to be ignored

### ISSUE THREAD

**Issue by albeekj** [TAMUArch/cookbook.windows_ad#93]
Hoping someone here can help. I am currently using Chef 12.9.41, windows_ad 0.5.3, and windows 2012r2. My ou has a space in it DEV automation,OU=TEST. When ever I try to join or create an object or join to an object, I get a consistent error. " SystemCallError: The user name or password is incorrect. - LogonUserW" What might I be doing wrong? It appears the cookbook ignores cmd\* information.  To work around this, I remove completely cmd or domain attributes and utilize "options".  However, to join the domain options are not available.  So there are no assumptions, the boxes are completely off the domain.  Finally, I have validated the creds work by going directly to the box and executing the necessary commands to create, join, and delete objects and they work.

**Comment by albeekj** [comment]
This is my workaround for creating the object
windows_ad_computer node.name do
  action :create
  domain_name node['test_cookbooks']['cmd_domain']
  ou node['test_cookbooks']['ou']
  options(
    'desc' => 'Vagrant Rake db_migrate task evaluation',
    'u' => node['test_cookbooks']['cmd_user'],
    'p' => node['test_cookbooks']['cmd_pass'],
    'd' => node['test_cookbooks']['domain_name']
  )
  only_if {powershell_out(node['test_cookbooks']['check']).stdout.strip.empty?}

**Comment by albeekj** [comment]
My join is as follows:
windows_ad_computer node.name do
  action :join
  ou "DEV automation/TEST"
  domain_pass node['test_cookbooks']['domain_pass']
  domain_user node['test_cookbooks']['domain_user']
  domain_name node['test_cookbooks']['domain_name']
  cmd_pass node['test_cookbooks']['cmd_pass']
  cmd_user node['test_cookbooks']['cmd_user']
  cmd_domain node['test_cookbooks']['cmd_domain']
  restart true
end

**Comment by derekgroh** [comment]
@albeekj Running debug mode are you able to see what the command line looks like for joining the domain?

Suggest running that manually on the same system and seeing if the operation completes successfully.

I recall seeing a similar error with my own testing, but can not recall what the situation was to actually trigger it.

**Comment by albeekj** [comment]
@derekgroh <https://github.com/derekgroh> In cmd_helper.rb @ line 39, I
placed the following to see the command output because debug didn't give me
much in terms of output:

   Chef::Log.info(''.center(150,'&'))
    Chef::Log.info( "[DEBUG] #{shellout.inspect}" )
    Chef::Log.info(''.center(150,'&'))

OUTPUT:

dsadd computer "CN=devtstrake02,OU=DEV automation,OU=TEST,DC=example,DC=cc"
-desc "Vagrant Rake db_migrate task evaluation"' process_status: nil
stdout: '' stderr: '' child_pid: nil environment: {} timeout: 600 user:
vagrant_vsphere_svc group:  working_dir:

Admittedly, I don't fully understand how shellout works, but the password
doesn't seem to be used.  Please help me understand, should I be passing
the password in via the options?



On Sat, May 7, 2016 at 3:41 AM, Derek Groh <notifications@github.com> wrote:

> @albeekj <https://github.com/albeekj> Running debug mode are you able to
> see what the command line looks like for joining the domain?
>
> Suggest running that manually on the same system and seeing if the
> operation completes successfully.
>
> I recall seeing a similar error with my own testing, but can not recall
> what the situation was to actually trigger it.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/TAMUArch/cookbook.windows_ad/issues/93#issuecomment-217622980>
>



-- 
Thank you,

Kaleb Albee

**Comment by derekgroh** [comment]
@albeekj this is the command that will run.  I notice that there is an extra `'`.  Try running the command below directly on your DC and seeing if it is successful or not. 
`
dsadd computer "CN=devtstrake02,OU=DEV automation,OU=TEST,DC=example,DC=cc"
-desc "Vagrant Rake db_migrate task evaluation"'
`

**Comment by albeekj** [comment]
@derekgroh the dsadd works fine.  The machine is part of the AD

**Comment by albeekj** [comment]
@derekgroh I have dug in a bit more validated we are using windows 2012r2 and tried to do a simple whoami with the following:  I get the exact same error every time.  Is there a switch or a value I am missing?


Ohai2u Administrator@tsttfsapp01!
chef (12.12.13)> cmd_pass = 'superSecret'
 => "superSecret"
chef (12.12.13)> cmd_user = 'vagrant_vsphere_svc'
 => "vagrant_vsphere_svc"
chef (12.12.13)> domain_name = 'example.cc'
 => "example.cc"
chef (12.12.13)> shellout = Mixlib::ShellOut.new('whoami', user: cmd_user, password: cmd_pass, domain: domain_name)
 => <Mixlib::ShellOut#41076672: command: 'whoami' process_status: nil stdout: '' stderr: '' child_pid: nil environment: {} timeout: 600 user: vagrant_vsphere_svc group:  working_dir:  >
chef (12.12.13)> shellout.live_stdout = $stdout
 => #<IO:<STDOUT>>
chef (12.12.13)> shellout.run_command
SystemCallError: The user name or password is incorrect. - CreateProcessWithLogonW
        from C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/mixlib-shellout-2.2.6-universal-mingw32/lib/mixlib/shellout/windows/core_ext.rb:329:in `create'
        from C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/mixlib-shellout-2.2.6-universal-mingw32/lib/mixlib/shellout/windows.rb:80:in `run_command'
        from C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/mixlib-shellout-2.2.6-universal-mingw32/lib/mixlib/shellout.rb:259:in `run_command'
        from (irb):6
        from C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.13-universal-mingw32/lib/chef/shell.rb:75:in `block in start'
        from C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.13-universal-mingw32/lib/chef/shell.rb:74:in `catch'
        from C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.13-universal-mingw32/lib/chef/shell.rb:74:in `start'
        from C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.13-universal-mingw32/bin/chef-shell:34:in `<top (required)>'
        from C:/opscode/chef/bin/chef-shell:63:in `load'
        from C:/opscode/chef/bin/chef-shell:63:in `<main>'
chef (12.12.13)>
chef >

**Comment by derekgroh** [comment]
@albeekj the credentials will be passed into the following code
`('#{new_resource.domain_name}\\#{new_resource.domain_user}', $secpasswd)`

If your domain is `example.cc` the code will evaluate that to be `example.cc\vagrant_vsphere_svc`.  Try changing your domain_name to just `example` (assuming this is your netbiosname)

**Comment by derekgroh** [comment]
We're taking some effort to clean up older issues for this repository. Please reply if you still wish for this to be worked on.
