### ISSUE TITLE
Domain Join Fails When Providing OU

### ISSUE THREAD

**Issue by jdgoins** [TAMUArch/cookbook.windows_ad#94]
The domain joining using the computer resource works fine unless I supply an OU. I've been using the old method in 0.4.4 to avoid this.

Chef-client version: 12.6.0
windows_ad version: 0.5.3

Example input:

```
windows_ad_computer test.com do
  action :join
  domain_pass 'password'
  domain_user 'test'
  domain_name test.com
  ou Accounts/test_ou
  restart false
end
```

Error output:

```
================================================================================
Error executing action `join` on resource 'windows_ad_computer[test.com]'
================================================================================

RuntimeError
------------
Failed to execute command.
STDOUT:
STDERR: dsquery failed:The specified domain either does not exist or could not be contacted.
type dsquery /? for help.
```

**Comment by jdgoins** [comment]
Is this still an active project?

**Comment by derekgroh** [comment]
Yep, just limited availability on my part

**Comment by derekgroh** [comment]
Hello @jdgoins 

From my initial view of your code, please put your ou string in quotes.

`ou "Accounts/test_ou"`

**Comment by jdgoins** [comment]
Hi @derekgroh 

I have tried it with quotes. I just tried again and it failed with the same dsquery error. This is only an issue when using the OU property. 

I'm not sure what mechanism was being used in 0.4.4, but domain joining to a specific OU worked very well in that version.

I tried this as well:

**attributes/default.rb**
```
default['cookbook']['domain_user'] = 'domainadmin'
default['cookbook']['domain'] = 'test.com'
default['cookbook']['ou'] = "Accounts/ChefManagedServers"
default['cookbook']['domain_password'] = 'testPa$$'
```

**recipes/default.rb**
```
windows_ad_computer node['cookbook']['domain'] do
  action :join
  domain_pass node['cookbook']['domain_password']
  domain_user node['cookbook']['domain_user']
  domain_name node['cookbook']['domain']
  ou node['cookbook']['ou']
  restart false
end
```

**Comment by farvour** [comment]
This seems like an issue with the assumption that RSAT is installed on the joining computer and should not be required at all if the full DN is given to the `Add-Computer` cmdlet. The recipe should probably check to see if a full DN is passed, and not attempt to look it up with `dsquery` for those of us that aren't installing RSAT on Server Core.

**Comment by derekgroh** [comment]
@farvour thanks for the input.  What method do you suggest using for validating if the input is the full DN and not a partial or incorrectly typed?

**Comment by fzbishopclark** [comment]
maybe 
`node[cookbook]['join_dsquery']=false` 
?  :-D

**Comment by donwlewis** [comment]
I realize this is a bit old, but you could just do a ruby LDAP query leveraging ruby gem.  I am doing that inside my cookbook actually...

**Comment by donwlewis** [comment]
If I get a chance I will try to put a PR for that.

**Comment by derekgroh** [comment]
We're taking some effort to clean up older issues for this repository.

If you still have a need for this feature, please submit the request to the Chef repository for resource windows_ad_join (https://github.com/chef/chef/blob/master/lib/chef/resource/windows_ad_join.rb) as this cookbook is no longer going to handle duplicating an existing resource.
