### ISSUE TITLE
Cannot add user to domain - You must hold the 'Replace a process level token'

### ISSUE THREAD

**Issue by dcallagh** [TAMUArch/cookbook.windows_ad#96]
Using the provided user add example.
Administrator is member of domain & enterprise admin
Have changed the password for Administrator in th edomain to see if this was the issue (local V domain) no luck.
Comes up with No error - CreateProcessAsUserW (You must hold the 'Replace a process level token' permission)

Vagrant is 1.8.1

$ vagrant provision win2012r2core
RSA 1024 bit CA certificates are loaded due to old openssl compatibility
==> win2012r2core: Running provisioner: chef_zero...
RSA 1024 bit CA certificates are loaded due to old openssl compatibility
RSA 1024 bit CA certificates are loaded due to old openssl compatibility
==> win2012r2core: Detected Chef (latest) is already installed
==> win2012r2core: Generating chef JSON and uploading...
RSA 1024 bit CA certificates are loaded due to old openssl compatibility
RSA 1024 bit CA certificates are loaded due to old openssl compatibility
==> win2012r2core: Running chef-client (local-mode)...
==> win2012r2core: [2016-07-28T21:50:34-07:00] INFO: Started chef-zero at chefzero://localhost:8889 with repository at C:/vagrant-chef/7b48616b1e74ef20bc277bc793cfd70a
==> win2012r2core:   One version per cookbook
==> win2012r2core:   nodes at C:/vagrant-chef/33d5b31c47b884fc6457ddac1602841f/nodes
==> win2012r2core:
==> win2012r2core: Starting Chef Client, version 12.13.13
==> win2012r2core: [2016-07-28T21:50:34-07:00] INFO: **\* Chef 12.13.13 ***
==> win2012r2core: [2016-07-28T21:50:34-07:00] INFO: Platform: x64-mingw32
==> win2012r2core: [2016-07-28T21:50:34-07:00] INFO: Chef-client pid: 696
==> win2012r2core: [2016-07-28T21:51:03-07:00] INFO: GET /organizations/chef/nodes/vagrant-2782842d
==> win2012r2core: [2016-07-28T21:51:03-07:00] INFO: Setting the run_list to ["recipe[windows_ad::binduser]"] from CLI options
==> win2012r2core:
==> win2012r2core: [2016-07-28T21:51:03-07:00] INFO: Run List is [recipe[windows_ad::binduser]]
==> win2012r2core: [2016-07-28T21:51:03-07:00] INFO: Run List expands to [windows_ad::binduser]
==> win2012r2core: [2016-07-28T21:51:03-07:00] INFO: Starting Chef Run for vagrant-2782842d
==> win2012r2core: [2016-07-28T21:51:03-07:00] INFO: Running start handlers
==> win2012r2core: [2016-07-28T21:51:03-07:00] INFO: Start handlers complete.
==> win2012r2core: resolving cookbooks for run list: ["windows_ad::binduser"]
==> win2012r2core: [2016-07-28T21:51:03-07:00] INFO: POST /organizations/chef/environments/_default/cookbook_versions
==> win2012r2core: --- POST BODY ---
==> win2012r2core: {"run_list":["windows_ad::binduser"]}
==> win2012r2core: --- END POST BODY ---
==> win2012r2core: [2016-07-28T21:51:05-07:00] INFO: Loading cookbooks [windows_ad@0.5.3, windows@1.44.1, chef_handler@1.4.0]
==> win2012r2core: Synchronizing Cookbooks:
==> win2012r2core:
==> win2012r2core:   - windows_ad (0.5.3)
==> win2012r2core:   - chef_handler (1.4.0)
==> win2012r2core:
==> win2012r2core:   - windows (1.44.1)
==> win2012r2core: Installing Cookbook Gems:
==> win2012r2core: Compiling Cookbooks...
==> win2012r2core: C:/opscode/chef/embedded/lib/ruby/2.1.0/x64-mingw32/dl.so: warning: already initialized constant DL::RUBY_FREE
==> win2012r2core: C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/net-ssh-3.2.0/lib/net/ssh/authentication/pageant.rb:16: warning: previous definition of RUBY_FREE was here
==> win2012r2core: DL is deprecated, please use Fiddle
==> win2012r2core: Converging 2 resources
==> win2012r2core:
==> win2012r2core: Recipe: windows_ad::binduser
==> win2012r2core:   \* windows_ad_user[Joe Smith] action create
==> win2012r2core:
==> win2012r2core:
==> win2012r2core:     ================================================================================
==> win2012r2core:     Error executing action `create` on resource 'windows_ad_user[Joe Smith]'
==> win2012r2core:     ================================================================================
==> win2012r2core:
==> win2012r2core:     Errno::NOERROR
==> win2012r2core:     --------------
==> win2012r2core:     No error - CreateProcessAsUserW (You must hold the 'Replace a process level token' permission)
==> win2012r2core:
==> win2012r2core:     Cookbook Trace:
==> win2012r2core:     ---------------
==> win2012r2core:     c:/var/chef/cache/cookbooks/windows_ad/libraries/cmd_helper.rb:39:in `shell_out'
==> win2012r2core:     c:/var/chef/cache/cookbooks/windows_ad/providers/user.rb:123:in`exists?'
==> win2012r2core:     c:/var/chef/cache/cookbooks/windows_ad/providers/user.rb:29:in `block in class_from_file'
==> win2012r2core:
==> win2012r2core:     Resource Declaration:
==> win2012r2core:     ---------------------
==> win2012r2core:     # In c:/var/chef/cache/cookbooks/windows_ad/recipes/binduser.rb
==> win2012r2core:
==> win2012r2core:       3: windows_ad_user "Joe Smith" do
==> win2012r2core:       4:   action :create
==> win2012r2core:       5:   domain_name "contoso.com"
==> win2012r2core:       6:   ou "users"
==> win2012r2core:       7:   options ({ "samid" => "JSmith",
==> win2012r2core:       8:          "upn" => "JSmith@contoso.com",
==> win2012r2core:       9:          "fn" => "Joe",
==> win2012r2core:      10:          "ln" => "Smith",
==> win2012r2core:      11:          "display" => "Smith, Joe",
==> win2012r2core:      12:          "disabled" => "no",
==> win2012r2core:      13:          "pwd" => "Passw0rd"
==> win2012r2core:      14:        })
==> win2012r2core:      15:   cmd_user "Administrator"
==> win2012r2core:      16:   cmd_pass "blah"
==> win2012r2core:      17:   cmd_domain "contoso.com"
==> win2012r2core:      18: end
==> win2012r2core:      19: windows_ad_group_member 'Joe Smith' do
==> win2012r2core:      20:   action :add
==> win2012r2core:      21:   group_name  'Domain Admins'
==> win2012r2core:      22:   domain_name 'contoso.com'
==> win2012r2core:      23:   user_ou 'Users'
==> win2012r2core:      24:   group_ou 'AD/Users'
==> win2012r2core:      25:   cmd_user "Administrator"
==> win2012r2core:      26:   cmd_pass "blah"
==> win2012r2core:      27:   cmd_domain "contoso.com"
==> win2012r2core:      28: end
==> win2012r2core:
==> win2012r2core:     Compiled Resource:
==> win2012r2core:     ------------------
==> win2012r2core:     # Declared in c:/var/chef/cache/cookbooks/windows_ad/recipes/binduser.rb:3:in`from_file'
==> win2012r2core:
==> win2012r2core:     windows_ad_user("Joe Smith") do
==> win2012r2core:       action [:create]
==> win2012r2core:       retries 0
==> win2012r2core:       retry_delay 2
==> win2012r2core:       default_guard_interpreter :default
==> win2012r2core:       declared_type :windows_ad_user
==> win2012r2core:       cookbook_name "windows_ad"
==> win2012r2core:       recipe_name "binduser"
==> win2012r2core:       domain_name "contoso.com"
==> win2012r2core:       ou "users"
==> win2012r2core:       options {"samid"=>"JSmith", "upn"=>"JSmith@contoso.com", "fn"=>"Joe", "ln"=>"Smith", "display"=>"Smith, Joe", "disabled"=>"no", "pwd"=>"Passw0rd"}
==> win2012r2core:       cmd_user "Administrator"
==> win2012r2core:       cmd_pass "blah"
==> win2012r2core:       cmd_domain "contoso.com"
==> win2012r2core:     end
==> win2012r2core:
==> win2012r2core:     Platform:
==> win2012r2core:     ---------
==> win2012r2core:     x64-mingw32
==> win2012r2core:
==> win2012r2core: [2016-07-28T21:51:06-07:00] INFO: Running queued delayed notifications before re-raising exception
==> win2012r2core:
==> win2012r2core: Running handlers:
==> win2012r2core: [2016-07-28T21:51:06-07:00] ERROR: Running exception handlers
==> win2012r2core: Running handlers complete
==> win2012r2core: [2016-07-28T21:51:06-07:00] ERROR: Exception handlers complete
==> win2012r2core: Chef Client failed. 0 resources updated in 32 seconds
==> win2012r2core: [2016-07-28T21:51:06-07:00] FATAL: Stacktrace dumped to c:/var/chef/cache/chef-stacktrace.out
==> win2012r2core: [2016-07-28T21:51:06-07:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
==> win2012r2core: [2016-07-28T21:51:06-07:00] FATAL: Errno::NOERROR: windows_ad_user[Joe Smith](windows_ad::binduser line 3) had an error: Errno::NOERROR: No error - CreateProcessAsUserW (You must hold the 'Replace a process level token' permission)
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.

**Comment by derekgroh** [comment]
This is a new chef run after the system has installed the domain controller?

Might be a unique permission required in core, https://technet.microsoft.com/en-us/library/dn221975(v=ws.11).aspx

Probably need to add the command: `ntrights +r SeAssignPrimaryTokenPrivilege -u <user>`

Sadly my test environment isn't up and running at my new gig, so confirmation might take a bit.

**Comment by dcallagh** [comment]
Yep. However it only happens if you use the specify user /domain/password. Once i realised the shellout to new cred was the issue i removed them. Strange though as the credentials are the same and for a domain admin....Perhaps its a consequence of using the same login and password as prior to domain join...
Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Derek Groh <notifications@github.com> Date: 29/07/2016  4:49 PM  (GMT+10:00) To: "TAMUArch/cookbook.windows_ad" <cookbook.windows_ad@noreply.github.com> Cc: dcallagh <dcallagh@iname.com>, Author <author@noreply.github.com> Subject: Re: [TAMUArch/cookbook.windows_ad] Cannot add user to domain - You must hold the 'Replace a process level token' (#96) 
This is a new chef run after the system has installed the domain controller?

Might be a unique permission required in core, https://technet.microsoft.com/en-us/library/dn221975(v=ws.11).aspx

Probably need to add the command: ntrights +r SeAssignPrimaryTokenPrivilege -u <user>

Sadly my test environment isn't up and running at my new gig, so confirmation might take a bit.

**Comment by derekgroh** [comment]
We're taking some effort to clean up older issues for this repository. Please reply if you still wish for this to be worked on.
