### ISSUE TITLE
windows_ad_computer errors when restart not set

### ISSUE THREAD

**Issue by roberto-mardeni** [TAMUArch/cookbook.windows_ad#98]
The examples show that the resource can be used without setting the restart attribute, but the attribute is defined as required.

Please update the examples to indicate so.

This commit broke the functionality: https://github.com/TAMUArch/cookbook.windows_ad/commit/73946fc6191a8d2f0d2fb7650fca02a68e88b6c3#diff-82457c8063b3841429fae3ae5f1f4e30

**Comment by derekgroh** [comment]
These changes have been merged, closing issue.
